### ISSUE TITLE
Query JSON RPC endpoints Step 4 references deprecated txpool add command.

### ISSUE THREAD

**Issue by mthurston** [0xPolygon/polygon-edge-docs#80]
**Description** 

while following the docs to setup using the [previously mentioned doc page](https://edge-docs.polygon.technology/docs/working-with-node/query-json-rpc#step-4-send-a-transfer-transaction) example, `txpool add`, I discovered the add subcommand has been deprecated as of [polygon-edge 452](https://github.com/0xPolygon/polygon-edge/pull/452).  I believe the analogous example of the same functionality using JSON RPC would be `/txpool_content`.  Running `txpool add -h` yields the following:  
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3211389/162340479-aad24ac4-9b02-4a4a-951f-7bc83377451d.png">

Running command as stated in docs yields the following:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/3211389/162340578-7dc0f2ee-928b-49e4-8338-927b4bf493d2.png">

**Your environment**
* 20.04.1-Ubuntu running bash shell.  
* polygon-edge.git@34498f1e
* compiled with go1.16 and structured per installation instructions from polygon-edge-docs

**Steps to Reproduce**
* Follow installation and init a single chain data-dir
* genesis creation with one bootnode and --pos and --premine:<validator node id from previous step>
* Start via `polygon-edge server` with the `--dev` flag.
* run command from *Query JSON RPC* -> *Step 4* from bash.  Move funds from validator 

**Expected**
added funds moved to wallet.  

**Actual** 
error (see description)

**Proposed Solution**
Following precedent set by change [polygon-edge 452](https://github.com/0xPolygon/polygon-edge/pull/452) document intended Transfer Transaction approach as two steps - *Step 4 - Create a Signed Transaction* and *Step 5 - Send a Transfer Transaction*.

**Comment by mthurston** [comment]
FYI - updated original issue to use template provided in docs site "Report an issue" section.

**Comment by Aleksao998** [comment]
@mthurston Thank you so much for opening this issue, you are right. 
I've created PR for fixing this issue and will take a look if there is something else outdated in the doc
