### ISSUE TITLE
Question: hardware requirements?

### ISSUE THREAD

**Issue by kirillt** [0xPolygon/polygon-edge-docs#81]
Are there any requirements to machine running Polygon Edge?

E.g. Polkadot requires minimum 64GB of RAM:
https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot

**Comment by ZeljkoBenovic** [comment]
Hi @kirillt ,

There are no minimum hardware requirements for running the Polygon Edge chain.
H/W requirements depend on the transaction load and the configuration on the chain.

If there is not much stress on your chain, you can run it pretty much on any server.

To get some idea of the hardware requirements and the TPS performance that you can achieve, with the specific hardware, you can take a look at [Performance Tests](https://edge-docs.polygon.technology/docs/performance-reports/overview) in our public docs.

**Comment by kirillt** [comment]
Thank you @ZeljkoBenovic
