### ISSUE TITLE
Private key for pre-mined wallet

### ISSUE THREAD

**Issue by jacobhjkim** [0xPolygon/polygon-edge-docs#87]
When creating the genesis file, I pre-mined with the following command.
```shell
$ polygon-edge genesis
    ...
    --premine 0x1010101010101010101010101010101010101010:1000000000000000000000
```
Where can I get the private key for the premine wallet?

**Comment by FrankDev34** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

**Comment by jacobhjkim** [comment]
Thanks, moved this issue to [here](https://github.com/0xPolygon/polygon-edge/discussions/555).
